// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://afvqysmjbkwxkjwkuvej.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFmdnF5c21qYmt3eGtqd2t1dmVqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYwMTg1MDQsImV4cCI6MjA2MTU5NDUwNH0.kcN0WbmdPV94hbLGuXimRUVA0cI21uT2mpXOa_k1mDs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});